[tool.pyright]
venv = ".venv"
venvPath = "."

[tool.ruff]
indent-width = 4
line-length = 100
select = ["E", "F", "I", "W"]

[tool.pytest.ini_options]
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = true
